---
- name: install ncbi-blast+ package (required by ecamber)
  apt: pkg=ncbi-blast+ state=installed
  tags: ecamber

- name: install muscle package (required by ecamber)
  apt: pkg=muscle state=installed
  tags: ecamber

- name: install python-dev
  apt: pkg=python-dev state=installed
  tags: biopython

- name: install library biopython
  command: pip install biopython==1.65
  tags: biopython

- name: Add R repository
  # On Ubuntu target: add R stable repository and install it.
  apt_repository: repo='deb http://cran.r-project.org/bin/linux/ubuntu trusty/' update_cache=yes 
  tags: R

- name: install R
  apt: pkg=r-base state=installed install_recommends=yes force=yes
  tags: R

- name: download prodigal
  get_url: url=https://github.com/hyattpd/Prodigal/archive/v2.6.3.tar.gz dest=/tmp/Prodigal-2.6.3.tar.gz
  tags: prodigal

- name: unarchive prodigal
  unarchive: src=/tmp/Prodigal-2.6.3.tar.gz dest=/usr/local/src copy=no
  tags: prodigal

- name: install prodigal
  command: make install chdir=/usr/local/src/Prodigal-2.6.3
  tags: prodigal

- name: cmake install (required for installing libdivsufsort)
  apt: pkg=cmake state=installed
  tags: andi

- name: download library libdivsufsort
  get_url: url=https://github.com/EvolBioInf/andi/releases/download/v0.9.4/libdivsufsort-2.0.2-1.tar.gz dest=/tmp/libdivsufsort-2.0.2-1.tar.gz
  tags: andi

- name: unarchive libdivsufsort
  unarchive: src=/tmp/libdivsufsort-2.0.2-1.tar.gz dest=/usr/local/src copy=no
  tags: andi

- name: create subdirectory build in libdivsufsort directory
  file: path=/usr/local/src/libdivsufsort-2.0.2-1/build state=directory
  tags: andi

- name: cmake libdivsufsort
  command: cmake install -DCMAKE_BUILD_TYPE="Release" .. chdir=/usr/local/src/libdivsufsort-2.0.2-1/build 
  tags: andi

- name: make libdivsufsort
  command: make install chdir=/usr/local/src/libdivsufsort-2.0.2-1/build 
  tags: andi

- name: download andi
  get_url: url=https://github.com/EvolBioInf/andi/releases/download/v0.9.4/andi-0.9.4.tar.gz dest=/tmp/andi-0.9.4.tar.gz
  tags: andi

- name: unarchive andi
  unarchive: src=/tmp/andi-0.9.4.tar.gz dest=/usr/local/src copy=no
  tags: andi

- name: configure andi
  command: ./configure CPPFLAGS="-I/usr/local/include" CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" chdir=/usr/local/src/andi-0.9.4
  tags: andi

- name: make andi
  command: make chdir=/usr/local/src/andi-0.9.4
  tags: andi

- name: make install andi
  command: make install chdir=/usr/local/src/andi-0.9.4
  tags: andi

