---
- name: install ncbi-blast+ package (required by ecamber)
  apt: pkg=ncbi-blast+ state=installed
  tags: ecamber

- name: install muscle package (required by ecamber)
  apt: pkg=muscle state=installed
  tags: ecamber

- name: install python-dev
  apt: pkg=python-dev state=installed
  tags: biopython

- name: install library biopython
  command: pip install biopython==1.65
  tags: biopython

- name: Add R repository
  # On Ubuntu target: add R stable repository and install it.
  apt_repository: repo='deb http://cran.r-project.org/bin/linux/ubuntu trusty/' update_cache=yes 
  tags: R

- name: install R
  apt: pkg=r-base state=installed install_recommends=yes force=yes
  tags: R

- name: install tcsh
  apt: pkg=tcsh state=installed
  tags: tcsh

- name: install gcj
  apt: pkg=gcj-jdk state=installed
  tags: gcj

- name: download prodigal
  get_url: url=https://github.com/hyattpd/Prodigal/archive/v2.6.3.tar.gz dest=/tmp/Prodigal-2.6.3.tar.gz
  tags: prodigal

- name: unarchive prodigal
  unarchive: src=/tmp/Prodigal-2.6.3.tar.gz dest=/usr/local/src/ copy=no creates=/usr/local/src/Prodigal-2.6.3
  tags: prodigal

- name: install prodigal
  command: make install chdir=/usr/local/src/Prodigal-2.6.3
  tags: prodigal

- name: cmake install (required for installing libdivsufsort)
  apt: pkg=cmake state=installed
  tags: andi

- name: download library libdivsufsort
  get_url: url=https://github.com/EvolBioInf/andi/releases/download/v0.9.4/libdivsufsort-2.0.2-1.tar.gz dest=/tmp/libdivsufsort-2.0.2-1.tar.gz
  tags: andi

- name: unarchive libdivsufsort
  unarchive: src=/tmp/libdivsufsort-2.0.2-1.tar.gz dest=/usr/local/src copy=no creates=/usr/local/src/libdivsufsort-2.0.2-1
  tags: andi

- name: create subdirectory build in libdivsufsort directory
  file: path=/usr/local/src/libdivsufsort-2.0.2-1/build state=directory
  tags: andi

- name: cmake libdivsufsort
  command: cmake install -DCMAKE_BUILD_TYPE="Release" .. chdir=/usr/local/src/libdivsufsort-2.0.2-1/build 
  tags: andi

- name: make libdivsufsort
  command: make install chdir=/usr/local/src/libdivsufsort-2.0.2-1/build 
  tags: andi

- name: download andi
  get_url: url=https://github.com/EvolBioInf/andi/releases/download/v0.9.4/andi-0.9.4.tar.gz dest=/tmp/andi-0.9.4.tar.gz
  tags: andi

- name: unarchive andi
  unarchive: src=/tmp/andi-0.9.4.tar.gz dest=/usr/local/src copy=no creates=/usr/local/src/andi-0.9.4
  tags: andi

- name: configure andi
  command: ./configure CPPFLAGS="-I/usr/local/include" CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" chdir=/usr/local/src/andi-0.9.4
  tags: andi

- name: make andi
  command: make chdir=/usr/local/src/andi-0.9.4
  tags: andi

- name: make install andi
  command: make install chdir=/usr/local/src/andi-0.9.4
  tags: andi

- name: download ecamber
  get_url: url=http://bioputer.mimuw.edu.pl/ecamber/software/ecamber_src_1.09.zip dest=/tmp/ecamber_src_1.09.zip
  tags: ecamber

- name: unarchive ecamber
  unarchive: src=/tmp/ecamber_src_1.09.zip dest=/usr/local/src copy=no creates=/usr/local/src/ecamber_src_1.09
  tags: ecamber

- name: get muscle path
  shell: which muscle
  register: MUSCLE
  tags: ecamber

- name: get blast+/tblastn path
  shell: which tblastn
  register: TBLASTN
  tags: ecamber

- name: configure ecamber
  template: src=templates/ecamber_config_aln_paths.j2 dest=/usr/local/src/ecamber/config/config_aln_paths.txt
  tags: ecamber

- name: get blast+/blastn path
  shell: which blastn
  register: BLASTN
  tags: ecamber

- name: get blast+/blastp path
  shell: which blastp
  register: BLASTP
  tags: ecamber

- name: get blast+/makeblastdb path
  shell: which makeblastdb
  register: MAKEBLASTDB
  tags: ecamber

- name: get prodigal path
  shell: which prodigal
  register: PRODIGAL
  tags: ecamber

- name: configure ecamber 2nd step
  template: src=templates/ecamber_config_extpaths.j2 dest=/usr/local/src/ecamber/config/config_extpaths.txt
  tags: ecamber

- name: configure ecamber 3rd step
  copy: src=files/config_resources.txt dest=/usr/local/src/ecamber/config/config_resources.txt
  tags: ecamber

- name: correction of ecamber python script
  replace:
    dest=/usr/local/src/ecamber/src/soft/utils/camber_format_utils.py
    regexp='left_bound, right_bound = tokens\[1\]\.strip\("complement\("\)\.split\("\.\."\)'
    replace='left_bound, right_bound = tokens[1].strip("complement(").strip(")").split("..")'
  tags: ecamber

- name: create directory opscan for shared data
  file: path=/usr/local/share/opscan state=directory
  tags: opscan

- name: copy opscan binary
  copy: src=files/opscan dest=/usr/local/bin/ mode=0755
  tags: opscan

- name: copy opscan matrix
  copy: src=files/BLOSUM60 dest=/usr/local/share/opscan/
  tags: opscan

- name: transfer coregenbuilder source files
  copy: src=files/coregenbuilder.tar.gz dest=/tmp/coregenbuilder.tar.gz
  tags: coregenbuilder

- name: unarchive coregenbuilder
  unarchive: src=/tmp/coregenbuilder.tar.gz dest=/usr/local/src copy=no
  tags: coregenbuilder

- name: create coregenbuilder etc directory
  file: path=/etc/coregenbuilder state=directory
  tags: coregenbuilder

- name: remove share/coregenbuilder dir if exists
  file: path=/usr/local/share/coregenbuilder state=absent
  tags: coregenbuilder

- name: create coregenbuilder share directory
  file: path=/usr/local/share/coregenbuilder state=directory
  tags: coregenbuilder

- name: configure coregenbuilder - step 1
  shell: mv /usr/local/src/coregenbuilder/src/* /usr/local/bin
  tags: coregenbuilder

- name: configure coregenbuilder - step 2
  shell: mv /usr/local/src/coregenbuilder/config/* /etc/coregenbuilder
  tags: coregenbuilder

- name: configure coregenbuilder - step 3
  shell: mv /usr/local/src/coregenbuilder/doc /usr/local/share/coregenbuilder
  tags: coregenbuilder

- name: configure coregenbuilder - step 4
  shell: mv /usr/local/src/coregenbuilder/data /usr/local/share/coregenbuilder
  tags: coregenbuilder

- name: configure coregenbuilder - step 5
  copy: src=files/config_env.txt dest=/etc/coregenbuilder
  tags: coregenbuilder

- name: configure coregenbuilder - step 6
  lineinfile: dest=/usr/local/bin/coregenebuilder regexp='^CGB_CONFIG=.*' line='CGB_CONFIG={{ CGB_CONFIG_PATH }}'
  tags: coregenbuilder

- name: transfer fasta2agp source files
  copy: src=files/FASTA2AGP.tar.gz dest=/tmp/FASTA2AGP.tar.gz
  tags: fasta2agp

- name: unarchive fasta2agp
  unarchive: src=/tmp/FASTA2AGP.tar.gz dest=/usr/local/src copy=no
  tags: fasta2agp

- name: compile fasta2agp
  command: gcj -O3 --main=FASTA2AGP FASTA2AGP.java -o fasta2agp chdir=/usr/local/src/FASTA2AGP/src
  tags: fasta2agp

- name: move fasta2agp binary file 
  shell: cp /usr/local/src/FASTA2AGP/src/fasta2agp /usr/local/bin
  tags: fasta2agp

- name: remove all archives from /tmp
  file: path=/tmp/{{ item }} state=absent
  with_items:
     - andi-0.9.4.tar.gz
     - coregenbuilder.tar.gz
     - ecamber_src_1.09.zip
     - libdivsufsort-2.0.2-1.tar.gz
     - Prodigal-2.6.3.tar.gz
     - FASTA2AGP.tar.gz
  tags: clean 

- name: Set motd 
  copy: src=files/motd dest=/etc mode=664
  tags: motd
  
