---
- name: install ncbi-blast+ package (required by ecamber)
  apt: pkg=ncbi-blast+ state=installed
  tags: ecamber

- name: install muscle package (required by ecamber)
  apt: pkg=muscle state=installed
  tags: ecamber

- name: install python-dev
  apt: pkg=python-dev state=installed
  tags: biopython

- name: install library biopython
  command: pip install biopython==1.65
  tags: biopython

- name: Add R repository
  # On Ubuntu target: add R stable repository and install it.
  apt_repository: repo='deb http://cran.r-project.org/bin/linux/ubuntu trusty/' update_cache=yes 
  tags: R

- name: install R
  apt: pkg=r-base state=installed install_recommends=yes force=yes
  tags: R

- name: download prodigal
  get_url: url=https://github.com/hyattpd/Prodigal/archive/v2.6.3.tar.gz dest=/tmp/Prodigal-2.6.3.tar.gz
  tags: prodigal

- name: unarchive prodigal
  unarchive: src=/tmp/Prodigal-2.6.3.tar.gz dest=/usr/local/src copy=no
  tags: prodigal

- name: install prodigal
  command: make install chdir=/usr/local/src/Prodigal-2.6.3
  tags: prodigal

